name: release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Release docker file
      - name: Build the Docker image
        run: docker build -t docker.pkg.github.com/hikhvar/mqtt2prometheus/mqtt2prometheus:latest -t docker.pkg.github.com/hikhvar/mqtt2prometheus/mqtt2prometheus:${GITHUB_REF##*/} .
      - name: Login to Github
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Publish latest image        
        run: docker push docker.pkg.github.com/hikhvar/mqtt2prometheus/mqtt2prometheus:latest
      - name: Publish tag image        
        run: docker push docker.pkg.github.com/hikhvar/mqtt2prometheus/mqtt2prometheus:${GITHUB_REF##*/} 
